### ISSUE TITLE
Define Organizer Team

### ISSUE THREAD

**Issue by erikauer** [cloud-native-austria/kcd-austria#1]
## Description

For the organisation of KCD Vienna we need a Core Team, which is responsible for the organisation of the event.

We need to define 5-8 people who will take on different responsibilities and who will then take care of their area.

#### Coordinator Role

- Invites to the regular meetings
- responsible that all team roles and responsibilities are assigned
- Responsible for the communication of the organisation team
- Support organisation team that everyone can work properly
- Takes over communication to the CNCF (e.g. email to kcd@cncf.io)
- Ensures that all topics are addressed and that the organisation of the event is covered in its entirety.
- Central overview of the whole event and time coordination with other roles to ensure that the topics are carried out on time.
- responsible that the event meets all the requirement of KCD (e.g. diversity, official cncf timelines and guidelines are followed)

#### Finance Role

- Determine how an who will handle money
- How Invoicing/Taxes are handled (legal entity)
- Responsible for legal issues
- Cost estimation of the event
- income and expense account
- define banking account we can use
- payments
- Check for Fundings

#### Marketing Role

- Creation of Marketing material (e.g. Social Media Posts, Sponsor Ship Slides ...)
- Definition of Sponsor Packages
- Define outbound communication plan and executes it (emails for sponsors, attendees, social channels)
- Creation of the Event Website
- Responsible to create ticketing page
- Define Speaker lineup and streams
- Design Kubernetes Community Logos
- Design and order Lanyards, Badges, Swag and materials we need for the event (handout material)
- Responsible for copyright topics
- Placement of Sponsors (Logos, etc.) regarding the sponsor package at the event
- Press plan
- Design Presentation Templates

#### Speaker Organiser Role

- Responsible to create the CFP
- Select Speakers and Talks
- Sponsor contracts

#### Sponsor Organiser Role

- Responsible to find Platinum, Gold, Silver, Bronze Sponsors

#### Venue Organiser Role

- Research for an venue and book it
- Responsible for ensuring that all technical conditions at the venue are met so that the conference can be held (e.g. lights and sound management, video, wifi)
- Responsible for ensuring compliance with fire and health care regulations etc.
- Responsible for hotel RFP
- Responsible for food and drinks
- Responsible for the event implementation on the day of the event (tables, chair are ordered and places, registration process is in place)
- Call for Volunteers (?)
- Evening activity booking (?)

### Suggested Team

The Core Team should be composed so that 1-2 people per role are filled. 2 people are needed for marketing.

**Comment by duffleit** [comment]
I would definitely add "Legal" as one Role or extend the Financial with this one (although it does imho not need to be the same person).

**Comment by erikauer** [comment]
> I would definitely add "Legal" as one Role or extend the Financial with this one (although it does imho not need to be the same person).

"- Responsible for legal issues" add this to the description of the financial role

**Comment by Saim-Safdar** [comment]
Marketing, social posting and Take over-communication to CNCF

**Comment by henrikrexed** [comment]
Marketing role or Speaker organizer role

**Comment by DrackThor** [comment]
Speaker organizer backup :)

**Comment by erikauer** [comment]
@thschue @DavidPHirsch should we close this issue by now as we already have our core team and responsibilites defined?

**Comment by DavidPHirsch** [comment]
I think we can close as Thomas has also added the info to the readme
