### ISSUE TITLE
Contract catering

### ISSUE THREAD

**Issue by jgrumboe** [cloud-native-austria/kcd-austria#117]

**Comment by erikauer** [comment]
Wrote to Gasthaus Figl (our caterer from last year) and gave him some additional details. (e.g. that we planning for 500 people this year)

I already have the written confirmation, that they will be available again for KCD 2024 to do catering.

**Comment by jgrumboe** [comment]
@erikauer This is done, rigth?

**Comment by DrackThor** [comment]
done by @erikauer
