### ISSUE TITLE
Find Sponsors

### ISSUE THREAD

**Issue by erikauer** [cloud-native-austria/kcd-austria#12]
## Description

In order to organise the financial means for the event, an essential pillar is to find sponsors for this event.

Use the sponsor packages defined in #9 as information for potential sponsors. 

### Sponsorship Pipeline

We currently track potential sponsors here:
https://github.com/orgs/cloud-native-austria/projects/2

So please add any  potential sponor to this project.

**Comment by DavidPHirsch** [comment]
We need 3 sponsors before opening the CFP

**Comment by thschue** [comment]
Current State:
* 3 Gold Sponsors
* 8 Silver Sponsors
* 5 Community Sponsors 

=> https://github.com/orgs/cloud-native-austria/projects/2/views/2?layout=table&filterQuery=status%3A%22Prepare+contract%22%2CConfirmed%2C%22All+parties+signed%22%2C%22Invoice+in+progress%22%2C%22Money+received%22%2C%22Social+media+announced%22%2C%22Artwork+received%22%2C%22Waiting+for+sponsor+to+sign%22&sortedBy%5Bdirection%5D=asc&sortedBy%5BcolumnId%5D=50863446&groupedBy%5BcolumnId%5D=50863446

**Comment by jgrumboe** [comment]
Last state:
3 Gold Sponsors
10 Silver Sponsors
6 Community Sponsors
