### ISSUE TITLE
Create CFP

### ISSUE THREAD

**Issue by erikauer** [cloud-native-austria/kcd-austria#14]
## Description

Create a CFP to get speakers for KCD Austria.

### Tooling

There should be a tool in place from CNCF to create CFPs called "SM Apply platform". Maybe we can use it to create the CFP for KCD Austria as well.

**Comment by DrackThor** [comment]
- [ ] @henrikrexed will look into CFP forms, structures and questions
- [ ] @henrikrexed will create a matrix to create a transparent ranking for CFP answers
- [ ] @DrackThor will have a look at possible CFP platforms; check what CNCF recommends and what others use(d)

**Comment by DrackThor** [comment]
- proposed tool by CNCF is SurveyMonkey -> https://apply.surveymonkey.com/
- Sample CFP: https://github.com/cncf/kubernetes-community-days/blob/main/speaker-resources/cfp.md 
  - DevOps Days CFPs: https://devopsdays.org/speaking/
- CFP Considerations: https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/program/scoring-guidelines/#overview

Proposal for our CFP:

- use Survey Monkey (as suggested by CNCF)
- use grading system 5-1 for each of the following criteria (as suggested by CNCF)
  - relevance
  - originality
  - soundness
  - quality of presentation
  - importance
  - experience of presenter
- have a single-blind review to ensure a diverse field of speakers
  - depending on the amout of proposals, have two independent reviews for each proposal
- have the following categories of talks
  - solo/dual presentations ~35min 
  - solo lightning talk ~5-7min
  - panel discussion ~35min / 3-5 speakers (min. 1 non-male)
- use the following fields for the CFP form
  - email
  - speaker name
  - talk title
  - talk category
  - CoC agreement
  - abstract
    - (optional) links to further information
  - speaker bio
  - speaker picture link
  - social media handle(s)
  - accessability needs
  - technical/non-technical talk (?)

**Comment by DrackThor** [comment]
> @DrackThor @henrikrexed we still need:
> 
> * preliminary agenda for the conference (just sessions and breaks) for the website
> * a list of the committee members
> * Deadline, notification date and dealine for slides

- ad agenda: provided in slack channel
- ad commitee members: agreed upon in last meeting
  - @henrikrexed 
  - @DrackThor 
  - @erikauer 
  - @DavidPHirsch 
  - @duffleit 
- ad deadline: 
  - CfP should be launched asap
  - speaker acceptance deadline around end of july (?)
  - slides deadline around beginning of september (?)

**Comment by DavidPHirsch** [comment]
@DrackThor @henrikrexed can we close this? Only item that could be missing is the evaluation matrix
