### ISSUE TITLE
Create event website

### ISSUE THREAD

**Issue by erikauer** [cloud-native-austria/kcd-austria#15]
## Description

Create an Event Website for KCD Austria.

### Tooling

CNCF recommends using Bevy platform for "Website and ticket support".

### Examples

- [KCD Munich 2022](https://community.cncf.io/events/details/cncf-kcd-munich-presents-kubernetes-community-days-munich-2022-1/) 
- [KCD Munich 2023](https://community.cncf.io/events/details/cncf-kcd-munich-presents-kcd-munich-2023/)
- [KCD France 2023](https://www.kcdfrance.fr/)
- [KCD Zurich 2023](https://kcdzurich.ch/)

**Comment by DavidPHirsch** [comment]
The request has been put in to create the group, i will let you know whe it is ready so we can start working on the content
