### ISSUE TITLE
Define Legal Entity

### ISSUE THREAD

**Issue by duffleit** [cloud-native-austria/kcd-austria#2]
## Description

For the organization of KCD Vienna, we need a Legal Entity under which the organization can take place. 
We need to have this for multiple reasons, like: 
* Allow official contracts between visitors and us (invoicing). 
* Allow official contracts between potential partners and us (sponsoring). 
* Allow official contracts between speakers and us (coverage of traveling costs).
* Allow official contracts between us and the venue (booking).
* Allow to manage and hold the budget/funds of this community (bank account).
* To avoid personal liability of the organization team.

### Potential Options
There is a range of options that could be used as legal entities: 
* _Verein_, which is not geared towards profit. This fits our goals. 
* _GmbH_, which reduces some of the bureaucracy that is given in a Verein.
* A _GmbH Light_, a simplified form in Austria for a GmbH, mainly reduces the _Stammeinlage_. 

### Role Models
There are already some organizations that use a Verein for similar reasons: 
* [Angular Austria](https://angular-austria.at/) to organize ongoing Angular Community Events.
* [Dot Net Austria](https://web.archive.org/web/20220528204231/https://dotnetdevs.at/team/) to organize ongoing .NET Community Events. 
* [Rescript Association](https://rescript-association.org/about) which organized [ReasonConf](https://www.reason-conf.com/) in Vienna.

We have already decided to reach out to those for further insights into the possible pros and cons of a _Verein_.

**Comment by duffleit** [comment]
Tom will gather the informations from Rescript Associations, I will talk to Angular Austria and Dot net Austria.

**Comment by jgrumboe** [comment]
I'm in contact with Rainer Stropek from Global Azure Austria.

**Comment by erikauer** [comment]
@erikauer ask lawyer and accountant about which entity would suits best for cncf related events non-profit company.

- Funding
- Taxes
- Legal

**Comment by erikauer** [comment]
Erik:

will ask boeb austria, about a more detailed pricing and clarify it for next week

Alois, David:

will ask dynartrace

**Comment by DavidPHirsch** [comment]
@AloisReitbauer and @tomstagl are checking if dynatrace can be the legal entity for this first edition

**Comment by erikauer** [comment]
@DavidPHirsch as decided in the meeting today, we go with Dynatrace as legal entity for the first event 2023.

So, we can close this ticket I think :) Feel free to do so, if you agree :)
