### ISSUE TITLE
Proposal: MoM and task assignments in GitHub

### ISSUE THREAD

**Issue by DrackThor** [cloud-native-austria/kcd-austria#20]
@cloud-native-austria/kcd-organizers how about we gather the meeting minutes (incl. task assignments) also in GitHub? \

I'm not particularly happy with having another system (Google doc) for our meeting protocols.\

Maybe we could have a "mom" folder in the repo root and a markdown doc for each meeting conducted by any member of the organizers group? This way we have everything in one place, transparent for the whole team - even the meetings not everybody attended (eg venue, CFP meetings,..)

**Comment by DavidPHirsch** [comment]
@DrackThor I think as discussed one of the main issues with using github is the difficulty of realtime collaboration.
If you want we can copy over the notes after every meeting, what do you think?

**Comment by DrackThor** [comment]
sounds good to me 👍 that way we have some transparency
