### ISSUE TITLE
Organizers

### ISSUE THREAD

**Issue by DavidPHirsch** [cloud-native-austria/kcd-austria#21]
select 3 organizers and add to CNCF https://github.com/cncf/kubernetes-community-days/issues/467

**Comment by DavidPHirsch** [comment]
Organizer 1: First and Last Name, Company, Title, Email, CNCF Slack Username
 Organizer 2: First and Last Name, Company, Title, Email, CNCF Slack Username
 Organizer 3: First and Last Name, Company, Title, Email, CNCF Slack Username

**Comment by erikauer** [comment]
Erik Auer, WhizUs GmbH, CEO, erik.auer@whizus.com, Erik Auer

**Comment by DavidPHirsch** [comment]
perfect, 
I spoke with Alois and he proposed I be listed on the Dynatrace side

David Hirsch, Dynatrace, OSPO Program Manager, David.hirsch@dynatrace.com, David Hirsch

**Comment by duffleit** [comment]
If you need one more: 
David Leitner, SQUER Solutions GmbH Co-Founder, david@squer.io
