### ISSUE TITLE
Talk organization/structure

### ISSUE THREAD

**Issue by DavidPHirsch** [cloud-native-austria/kcd-austria#22]

**Comment by DavidPHirsch** [comment]
How to structure the tracks, typoes of talks, durations, themes

**Comment by DavidPHirsch** [comment]
please add others if needed

**Comment by DrackThor** [comment]
@henrikrexed and I had the Idea to have more but shorter talks; something like lightning talks?
-> therefore we could have more speakers and more diversity.

depending on the venue I would propose to have one "bigger" stage for keynotes and one for lightning talks.

**Comment by henrikrexed** [comment]
lighting talks: 15 min
Speaking track or co spenaking: 30min

We should include sponsor talks as well. What about adding workshops of 90min the first day?

**Comment by DrackThor** [comment]
maybe we can also have a panel discussion on the "main" stage. end-users/customers and established engineers and/or maintainers etc.

probably also have 1/2/3 workshops at a "pre-day/evening". afternoon before the first day, meet-and-greet organizers/speakers

we need to consider that each/some sponsors will also want to have a speaking slot (30min)
-> maybe have a "small" stage in the expo roon for sponsor-presentations during coffee breaks

by now, we think that we at least need the following rooms at the venue:
- one main room/main stage
- one/two side-stages in a dedicated room
- an expo room for sponsors, maintainers,..
- a dedicated chillout area
