### ISSUE TITLE
Streaming setup 

### ISSUE THREAD

**Issue by tomstagl** [cloud-native-austria/kcd-austria#27]
We need to find a partner who takes care about the streaming setup.

**Comment by jgrumboe** [comment]
As we talked about it yesterday, we aim only to record the sessions and not stream them live.
I'm in clarification with our internal department as this partner.

**Comment by thschue** [comment]
Currently clarifying if we do this and who is doing this.

**Comment by thschue** [comment]
"No, we won't have streaming."
