### ISSUE TITLE
Check if we can use fundings/grants

### ISSUE THREAD

**Issue by erikauer** [cloud-native-austria/kcd-austria#3]
## Description

In order to finance a part of the event, the possibility should be evaluated whether there are public fundings / grants that support individual parts or the event as a whole.

### Suggestions

There were already some suggestions we could evaluate:

- https://www.vienna.convention.at/de/veranstaltungsplanung/foerderungen-fuer-veranstaltungen/vienna-meeting-fund-2022-2024
- https://wirtschaftsagentur.at/foerderungen/aktuelle-programme/fe-kommunikation-79/
- https://transparenzportal.gv.at/tdb/tp/situation/npo/sonstige/veranstaltungen-konferenzen/1032663.html

**Comment by erikauer** [comment]
I already reached out to some institutes in vienna and possible fundings that we can probably use:

<google-sheets-html-origin><style type="text/css"></style>

Förderung von Kommunikationsprojekten der Forschungs- und Entwicklungsbranche | Information: https://wirtschaftsagentur.at/foerderungen/aktuelle-programme/fe-kommunikation-79/Documents: https://cockpit.wirtschaftsagentur.at/Cockpit/Cockpit.aspx?target=2111927&&select=4743385 | General NotesAkonto seems possible - discuss this with next call with Edina.20.03.2023Edina Elezi: It is not necessary, that a company already exists for a certain amount of time. It just need be fully founded already, when we request a funding.15.03.2023Had a call with Edina Elezi (+43 1 25200 423). She is not sure if the company should already exist for a while that we are able to request a funding. She will contact me tomorrow with further details. Available with Verein or GmbH.
-- | -- | --
Vienna Meeting Fund 2022-2024 | Information: https://www.vienna.convention.at/de/veranstaltungsplanung/foerderungen-fuer-veranstaltungen/vienna-meeting-fund-2022-2024Guidelines: https://www.vienna.convention.at/resource/blob/428122/15dab2d2a1aed4dd2c7d835e676497c0/rl-meeting-fund-2022-2024-de-data.pdf | 21.03.2023Payout: After the event we need to send them all the documents and invoices to proof our costs and after the have proofen everything, the pay out the requested fundings.15.03.2023Had a call with Markus Heigl (+43 1 211 14 520) markus.heigl@vienna.info.Funding should be accurate for our event.Requirement: We need to state (estimate), that at least 50% of our visitors stay overnight in vienna.
Invitation of the Mayor to the Mayor's Office Vienna |   | 21.03.2023Had a call with an event organizer of sec4dev. They invited the mayor and they sponsor half of a dinner as an evening programm. All conference participants can attend the dinner. The dinner takes place in the city hall or a Heuriger.
Kultur Förderungen Übersicht Stadt Wien | https://www.wien.gv.at/kultur/abteilung/foerderungen/ |  
Wissenschaft & Forschung | https://www.wien.gv.at/amtshelfer/kultur/projekte/subventionen/wissenschaft-und-forschung.html |

**Comment by erikauer** [comment]
Status:
Förderung von Kommunikationsprojekten der Forschungs- und Entwicklungsbranche

Finalised project documentation in the online portal. todo: company information and signing of dynatrace

**Comment by tomstagl** [comment]
Quick update:

- Company info is still in process. That includes financial data plus personal data. Good news is, the data for the GmbH is ready and needs only to be entered
- Employee information - same as Company Information
- We are currently in touch with Wirtschaftsagentur to schedule a review round. 

We still need to hold off with activities and we can move forward as soon as the application is entered.

**Comment by tomstagl** [comment]
We've submitted one funding request on the 5th of June.

**Comment by DavidPHirsch** [comment]
@erikauer @Thomas which funding opportunities will we still try and what are the deadlines, I will add them to the roadmap so we have a better timeline

**Comment by erikauer** [comment]
Status:

-) prepared everything for the request of vienna meeting fund and forwarded it to @tomstagl and @DavidPHirsch.
Please let us know, when you sent out the request for the funding

-) prepared the letter for the mayor of vienna and asked for feedback in the community slack channel - if no one will do a change request, I will send it tomorrow morning to the mayor.
