### ISSUE TITLE
Find and organize Hotels for Visitors

### ISSUE THREAD

**Issue by DavidPHirsch** [cloud-native-austria/kcd-austria#33]
find hotels that are close to the venue with good pricing and have blocked off rooms for keynote speakers and maybe other attendees

**Comment by DavidPHirsch** [comment]
- [ ] Holiday Inn Vienna South 
- [ ] Phils Place
- [ ] Arthur Garden Inn
- [ ] Campanile Vienna South
- [ ] 7 Days Premium Hotel Vienna South

**Comment by thschue** [comment]
@erikauer: I think you worked on this, right? May we update and close this?

**Comment by erikauer** [comment]
Currently 3 hotels are responded and we got an official offer. All offers are in google drive and published on our event page.
