### ISSUE TITLE
Find and book a venue

### ISSUE THREAD

**Issue by erikauer** [cloud-native-austria/kcd-austria#4]
## Description

For KCD Austria a venue is to be booked.

The venue should fulfil the following conditions:

- Safety regulations, fire regulations etc. are observed (possibly you can book this directly when booking the venue ???)
- Ensure sound, lighting, video and wifi are covered for the venue (we may also be able to ask for technical support contacts when booking the venue)
- Check availability of Tables / Chairs for the event

## Additional information

Some venues were already discussed (but not decided yet): 

-) Ottakringer Brauerei
-) Technikum

Other options should also be looked at (possibly also compare prices etc.)

**Comment by tomstagl** [comment]
fyi, I've been in touch with FH Technikum about another topic and I also asked if they're open to host that event. They have two rooms with a 200 pax capacity each plus smaller auditoriums

**Comment by DavidPHirsch** [comment]
I will reach out the the venues listed here for estimates https://docs.google.com/document/d/1pCSifd23tgrom8caBWQCMKJGNWjRM82A9wF2hS5wg7Y/edit#

**Comment by DavidPHirsch** [comment]
- [ ] Aula der Wissenschaften
- [ ] Austrian National Library
- [ ] Colosseum21
- [ ] Expedithalle
- [ ] Kursalon Betriebs 
- [ ] Leopold museum
- [ ] MAK - Museum of applied arts
- [ ] Musikverein Wien
- [ ] Palais Auersperg
- [ ] Palais Berg
- [ ] Palais Niederösterreich
- [ ] TU Wien
- [ ] Wiener Börensale

**Comment by entlein** [comment]
We re waiting to hear from you if you find the TUW rooms suitable or not. There was some discussion on slack that the rooms are not good enough.

**Comment by DavidPHirsch** [comment]
booked cineplexx wienerberg
