### ISSUE TITLE
Setup Operations team/volunteers

### ISSUE THREAD

**Issue by DavidPHirsch** [cloud-native-austria/kcd-austria#41]
- [ ] Decide the number of volunteers (~20)
- [ ] How many per organization
- [ ] Open call in July

**Comment by thschue** [comment]
Trying to find out who is responsible for this

**Comment by DrackThor** [comment]
I guess we've already talked about the number and roles of volunteers while having a look at the miro board.
@DavidPHirsch can you help me out here?
