### ISSUE TITLE
Define Sponsor Packages

### ISSUE THREAD

**Issue by erikauer** [cloud-native-austria/kcd-austria#5]
## Description

So that we can offer potential sponsors individual packages in different sizes, these packages are to be defined concretely.

Usually in CNCF there are following kind of packages:

- Platinum
- Gold
- Silver
- Bronze
- Community
- Media Partner

For each package are

- Package price
- Services of the package

to be defined.

In addition, you can define (if you think it makes sense) optional packages that can be booked apart from the packages. For example:

- Coffee break sponsored by xxx
- Room / Stream sponsored by xxx
- Lanyards sponsorship

(Just be creative :) )

### Helpful links

- Link to the Sponsor Packages in Munich: https://docs.google.com/presentation/d/1apL6B7Lh9T4NuUidxGe6rkyQEFzr66d67BDThOIIgdI/edit#slide=id.p1 (maybe this can be used as reference how we can define the packages)

**Comment by DavidPHirsch** [comment]
@erikauer @duffleit David Reyzek @niklas447 
could you take this?

**Comment by erikauer** [comment]
Meeting Notes from Meeting 4.4.2023:

@erikauer will contact Thomas Stagl and finalise the current packages together with him

**Comment by tomstagl** [comment]
Sponsor packages have been updated to reflect the 'no booth' situation.
Location specific information is in the slide deck
Number of speakers is also included

https://docs.google.com/presentation/d/1k_yyiFd-z7OWpCk7So9aqs79jtTVO7ZZ/edit#slide=id.g24b247b54d3_0_205
