### ISSUE TITLE
Social Media timeline planning

### ISSUE THREAD

**Issue by jgrumboe** [cloud-native-austria/kcd-austria#80]
Invite and social media posts to be send out by hosts, the following list are just ideas. Please correct, add or remove as needed 
--

- [x] Call for speakers
- [ ] Call for speakers closing
- [ ] Reminder: Early Bird Reg ending
- [ ] Confirmation of speakers
- [ ] Early Bird Reg to End
- [ ] IN-PERSON:Email speaker information including close by hotel, connection information A/V, speaker dinner confirmation + details (if applicable), +1 allowed for the event, speaker discount codes, deadlines
- [ ] VIRTUAL:Email speaker information including connection information A/V, speaker discount codes, deadlines.
- [ ] Last chance for hotel room rate (in-person)
- [ ] Don't miss out
- [ ] Looking forward to seeing you
- [ ] Last chance to attend
- [ ] See you soon
- [ ] Post conference survey

**Comment by erikauer** [comment]
@KatharinaSick already has collected a list of all necessary and possible social media posts (see above) - no further planning needed.
